language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.11
  - 2.12.4

cache:
  yarn: true
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.ivy2/local
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

before_cache:
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jobs:
  include:
    - stage: deploy
      scala: 2.12.4
      script: sbt doc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: js/target/scala-2.12/api/
        on:
          branch: doc
